name: Insufficient Logging Demo
on: [push]

jobs:
  insecure-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Delete files without logging
        run: |
          echo "Running dangerous cleanup..." > /dev/null
          rm -rf some_folder/
